import { FormEvent, useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import type { Deposit } from "../lib/types";
import { money, dateTime } from "../lib/format";
import { useAuth } from "../context/AuthContext";

type Method={id:string;name:string;account_number:string;instructions:string|null};
export default function AddFunds(){
  const {user}=useAuth(); const [methods,setMethods]=useState<Method[]>([]); const [method,setMethod]=useState(""); const [amount,setAmount]=useState(""); const [tx,setTx]=useState(""); const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [deposits,setDeposits]=useState<Deposit[]>([]);
  const load=()=>{if(!user)return; supabase.from("payment_methods").select("*").eq("status","active").order("sort_order").then(({data})=>{setMethods((data??[]) as Method[]);if(data?.[0])setMethod(data[0].id)});supabase.from("deposits").select("*").eq("user_id",user.id).order("created_at",{ascending:false}).then(({data})=>setDeposits((data??[]) as Deposit[]));};
  useEffect(load,[user?.id]);
  const submit=async(e:FormEvent)=>{e.preventDefault();setError("");setMessage("");const n=Number(amount);if(n<=0)return setError("Enter a valid amount.");const {error}=await supabase.from("deposits").insert({user_id:user!.id,payment_method_id:method,amount:n,transaction_id:tx.trim()});if(error)setError(error.message);else{setMessage("Deposit submitted for manual verification.");setAmount("");setTx("");load();}};
  return <div className="mx-auto max-w-4xl"><h1 className="text-3xl font-bold text-white">Add Funds</h1><div className="mt-7 grid gap-6 lg:grid-cols-2"><div className="card p-6"><h2 className="font-bold text-white">Manual Payment</h2><p className="mt-2 text-sm text-slate-400">Send the amount manually, then submit the transaction ID. Your balance is credited only after admin approval.</p><form onSubmit={submit} className="mt-6 space-y-4"><select className="input" value={method} onChange={e=>setMethod(e.target.value)}>{methods.map(m=><option value={m.id} key={m.id}>{m.name} — {m.account_number}</option>)}</select><input className="input" type="number" min="1" step="0.01" placeholder="Amount (৳)" value={amount} onChange={e=>setAmount(e.target.value)} required /><input className="input" placeholder="Transaction ID" value={tx} onChange={e=>setTx(e.target.value)} required />{methods.find(m=>m.id===method)?.instructions&&<div className="rounded-xl bg-white/5 p-4 text-sm text-slate-300">{methods.find(m=>m.id===method)?.instructions}</div>}{error&&<div className="rounded-xl bg-red-500/10 p-3 text-sm text-red-300">{error}</div>}{message&&<div className="rounded-xl bg-emerald-500/10 p-3 text-sm text-emerald-300">{message}</div>}<button className="btn-primary w-full">Submit Deposit</button></form></div><div className="card p-6"><h2 className="font-bold text-white">Deposit History</h2><div className="mt-5 space-y-3">{deposits.map(d=><div className="rounded-xl bg-white/5 p-4" key={d.id}><div className="flex justify-between"><span className="text-white">{money(d.amount)}</span><span className="text-xs text-slate-400">{d.status}</span></div><div className="mt-1 text-xs text-slate-500">{d.transaction_id} · {dateTime(d.created_at)}</div></div>)}{!deposits.length&&<div className="py-10 text-center text-sm text-slate-500">No deposits yet.</div>}</div></div></div></div>;
}